### PR TITLE
Rebase to upstream v0.58.0

### PR DESCRIPTION
**Pull request by creydr**
Inspired by the commit description for #209 

Identify carry commits:

```
git remote update
git log --oneline --no-merges v0.58.0..openshift/master
```

Note that the `UPSTREAM: <carry>:` prefix was added to any new commits to carry since the previous rebase. This will make new carry commits easy to identify alongside prior carry commits.

After identifying the carry commits, the next step is to create the new commit-tree that will be used for the rebase and then cherry pick the carry commits into the new branch.

The following commands cover these steps:

Process

```
$ git remote update # make sure we update our refs
$ git checkout v0.58.0 # upstream kubernetes-nmstate 0.52.4 commit tag
$ git checkout -b merge-tmp # create a branch to do our merge work from
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge nmstate/kubernetes-nmstate v0.58.0' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F -
deadbeef12345678 # id of new merge commit, output by the previous command
$ git branch merge-0.58.0 deadbeef12345678 # create a new branch for the cherry-pick work
$ git checkout merge-0.58.0 # make sure we are on the proper branch
$ git cherry-pick <carry commits>
```

* My 0.58.0 merge commit from the above process is (620f846a).
* With the merge-0.58.0 branch in place, I cherry picked the carry commits since `merge nmstate/kubernetes-nmstate v0.52.4` 95d87e7 (#209). 
* The `Updating openshift-kubernetes-nmstate-handler images to be consistent with ART Reconciling...` commits were squashed into `Update Dockerfile images to match ART`
* As I wasn't aware of the `UPSTREAM: <carry>:` prefix practice, I renamed my commits in this repo accordingly (4fe0d7a1 & 5abb1776). Same was done for commit 2e67701c which didn't have the prefix.
* Didn't carry the commit `Sync Dockerfile.openshift with u/s` (7b329dd0), as this was done in u/s ee3e8963

Carried Commits (applied bottom to top / oldest first):

```
UPSTREAM: <carry>: update naming convention
UPSTREAM: <carry>: Fix OPM index build
UPSTREAM: <carry>: Add machineconfigs before running e2e tests on OCP
UPSTREAM: <carry>: Define the suggested namespace for NMState CR
UPSTREAM: <carry>: Update Dockerfile images to match ART
UPSTREAM: <carry>: Add ocp-e2e-tests script
UPSTREAM: <carry>: Add manifests to .PHONY in Makefile
UPSTREAM: <carry>: Add manifests for 4.9
UPSTREAM: <carry>: Add manifests for 4.8
UPSTREAM: <carry>: Add manifests for 4.7
UPSTREAM: <carry>: Add midstream approvers and reviewers
```

**Release note**:
```release-note
Rebase to nmstate upstream v0.58.0
```

Draft this PR, until the issues with the e2e tests got resolved.

### CODE REVIEW

**Comment by creydr** [comment]
I created a PR to fix the e2e tests in u/s (https://github.com/nmstate/kubernetes-nmstate/pull/873). I would wait until the changes are in upstream and then cherry-pick them to have them here.
Alternatively I could skip the failing tests, so we have this PR merged (but I think the u/s PR also affects the CI integration into prow).

**Comment by cybertron** [comment]
Interestingly, I tested this version of the PR and it passed:
```
Ran 50 of 73 Specs in 3920.361 seconds
SUCCESS! -- 50 Passed | 0 Failed | 1 Pending | 22 Skipped
PASS
```
Which doesn't make sense if the upstream patch hasn't merged and we're not filtering the new tests. Maybe there's a timing/ordering factor to the failures?

**Comment by creydr** [comment]
> Interestingly, I tested this version of the PR and it passed:
> 
> ```
> Ran 50 of 73 Specs in 3920.361 seconds
> SUCCESS! -- 50 Passed | 0 Failed | 1 Pending | 22 Skipped
> PASS
> ```
> 
> Which doesn't make sense if the upstream patch hasn't merged and we're not filtering the new tests. Maybe there's a timing/ordering factor to the failures?

One of the patches was in u/s and is included in v0.58 (ba0eeab). The reason why it succeeds currently is, because the secondary interfaces of your master nodes are set to down (probably from one of a previous test run, which didn't have the patch to clean up properly), so the AfterEach of your suite doesn't complain.
If you run it on a fresh installed ocp / dev-scripts cluster (on which the secondary nics (in our case) are set to `up` initially), the current test should fail. This is addressed by my u/s patch (https://github.com/nmstate/kubernetes-nmstate/pull/873) which is just waiting for the tests to pass, before it gets merged :smile:

**Comment by creydr** [comment]
@cybertron I cherry-picked the commit from u/s into this branch an added a note in the commit message (9498a6c), that it can be removed on the next rebase as it should be included in the release from u/s.

**Comment by creydr** [comment]
I run the test tonight on a fresh installed dev-scripts / ocp cluster and it passed:

```
Ran 50 of 73 Specs in 2950.681 seconds
SUCCESS! -- 50 Passed | 0 Failed | 1 Pending | 22 Skipped
PASS
```

**Comment by cybertron** [comment]
Cool, let's do this then. I had one failure in my test run, but it looks like a flake to me.
/approve
/lgtm

**Pull request merged**
