### PR TITLE
OPNET-256: Move from version-specific to stable channel

### PR DESCRIPTION
**Pull request by mkowalski**
Contributes-to: [OPNET-256](https://issues.redhat.com//browse/OPNET-256)

### CODE REVIEW

**Comment by cybertron** [comment]
Are check-generate-bundle and unit not returning because this is in draft state? That's the main thing I'm interested in for this change.

**Comment by mkowalski** [comment]
> Are check-generate-bundle and unit not returning because this is in draft state? That's the main thing I'm interested in for this change.

They are, I just didn't run them in this particular iteration. But look at https://prow.ci.openshift.org/pr-history/?org=openshift&repo=kubernetes-nmstate&pr=353 and we had them green before. After the last change I just didn't rerun them because the last change was in the file not consumed by those

**Pull request merged**
