### PR TITLE
OCPBUGS-12970: Drop machine-config workaround from e2e tests

### PR DESCRIPTION
**Pull request by cybertron**
Thanks to some changes upstream in the e2e test suite we no longer need to do this workaround. Waiting for the entire cluster to reboot is now a waste of time and likely contributing to the timeouts that occur on a regular basis.

**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by dougsland** [comment]
tried that change last week and not flying with e2e. I got 4 errors. Let's see how CI see it, hope it just pass.

**Comment by cybertron** [comment]
/test e2e-handler-sdn-ipv4

Failures appear unrelated.

**Pull request merged**
