### PR TITLE
[DownstreamMerge] Rebase to upstream/main (2022-06-30)

### PR DESCRIPTION
**Pull request by creydr**
Inspired by the commit description for #243 

Identify carry commits:

```
git remote update
git log --oneline --no-merges upstream/main..openshift/master
```

Note that the `UPSTREAM: <carry>:` prefix was added to any new commits to carry since the previous rebase. This will make new carry commits easy to identify alongside prior carry commits.

After identifying the carry commits, the next step is to create the new commit-tree that will be used for the rebase and then cherry pick the carry commits into the new branch.

The following commands cover these steps:

Process

```
$ git remote update # make sure we update our refs
$ git checkout upstream/main
$ git checkout -b merge-tmp # create a branch to do our merge work from
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge nmstate/main 2022-06-30' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F -
deadbeef12345678 # id of new merge commit, output by the previous command
$ git branch merge-main-20220630 deadbeef12345678 # create a new branch for the cherry-pick work
$ git checkout merge-main-20220630 # make sure we are on the proper branch
$ git cherry-pick <carry commits>
```

* My merge commit from the above process is (744a66143).
* With the merge branch in place, I cherry picked the carry commits since `merge nmstate/kubernetes-nmstate v0.71.0` 84742ae5b. 

Carried Commits:

* `UPSTREAM: <carry>: Add midstream approvers and reviewers` (535fa8a81)
* `UPSTREAM: <carry>: Add manifests for 4.7` (bd0cf7034)
* `UPSTREAM: <carry>: Add manifests for 4.8` (af5e94d3f)
* `UPSTREAM: <carry>: Add manifests for 4.9` (b6778f93b)
* `UPSTREAM: <carry>: Add manifests to .PHONY in Makefile` (cfabf9865)
* `UPSTREAM: <carry>: Add ocp-e2e-tests script` (a78a700e2)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (bc9e34a7c)
* `UPSTREAM: <carry>: Define the suggested namespace for NMState CR` (62c2026a6)
* `UPSTREAM: <carry>: Add machineconfigs before running e2e tests on OCP` (42479c518)
* `UPSTREAM: <carry>: update naming convention` (a4093d8db)
* `UPSTREAM: <carry>: Update dockerfile to match ART` (c4f044e0a)
* `UPSTREAM: <carry>: Remove serviceaccount manifest` (5c84fd957)
* `UPSTREAM: <carry>: Provide default NMState CR` (464f99205)
* `UPSTREAM: <carry>: Skip e2e tests which are not supported on OVN` (80af39f0e)
* `UPSTREAM: <carry>: Add 4.10 release OLM manifests` (112af2c25)
* `UPSTREAM: <carry>: add arm64 to 4.10 CSV` (9857bf635)
* `UPSTREAM: <carry>: Add ppc64le and s390x to 4.10 CSV` (89957ae07)
* `UPSTREAM: <carry>: Fix JSON error in initialization resource` (e29ee0092)
* `UPSTREAM: <carry>: Update OWNERS` (9a91ba0d4)
* `UPSTREAM: <carry>: Switch to dnf in Openshift handler image` (24267ed9d)
* `UPSTREAM: <carry>: Add disconnected annotation for OperatorHub` (430895e5c)
* `UPSTREAM: <carry>: enable all archs in nmstate example CR` (c6e4bd42c)
* `UPSTREAM: <carry>: Add ssh proxy for e2e tests in CI` (23cfe9799)
* `UPSTREAM: <carry>: Remove initialization resource from CSV` (cea51d13f)
* `UPSTREAM: <carry>: Apply SCC in e2e tests when reinstalling operator in another namespace` (3a1e61e17)
* `UPSTREAM: <carry>: Add make target to run operator e2e tests against ocp` (25ab9205c)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (eb692ce60)
* `UPSTREAM: <carry>: Add operators app label in CSV` (725ea1bac)
* `UPSTREAM: <carry>: Do not ignore parameters for ocp tests` (8b9e18cfe)
* `UPSTREAM: <carry>: Add manifests for 4.11` (f54ac11d4)
* `UPSTREAM: <carry>: Fix ssh-ci.sh for dualstack environments` (f5dce6130)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (351769a55)
* `UPSTREAM: <carry>: Add qosClass to operator CSV` (5ccb81be9)
* `UPSTREAM: <carry>: add priority class to operator CSV` (234922cee)
* `UPSTREAM: <carry>: Rerun flaky e2e tests` (c8fa90dc4)
* `UPSTREAM: <carry>: Update 4.11 CSV file after rebase` (274a10851)
* `UPSTREAM: <carry>: Update NMState CRD` (b8fa0b177)
* `UPSTREAM: <carry>: Set SSH env correctly for operator e2e tests` (944e61ddf)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (6eb343cdc)

I squashed the commits a06963efd and b81d2d342 with 274a10851, as they were missed in 36e01dcf6.
In addition I updated the CSV file so it aligns with the latest changes from this rebase (4309b0daf).

**Release note**:
```release-note
Rebase to kubernetes-nmstate to latest upstream main
```

### CODE REVIEW

**Comment by cybertron** [comment]
It looks like the same test has failed every time. There might be an actual problem here (maybe the ovn job skips the problematic one?).

**Comment by cybertron** [comment]
/lgtm

Never mind then. :-)

**Comment by creydr** [comment]
> It looks like the same test has failed every time. There might be an actual problem here (maybe the ovn job skips the problematic one?).

@cybertron first I thought this is because the job was a flaky one. But looking into prow master seems to fail continuously on the nightly since june 17th (code freeze?!?): https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-kubernetes-nmstate-master-e2e-handler-sdn-ipv4-nightly-periodic

**Pull request merged**
