### PR TITLE
OPNET-205: update manifest for 4.13

### PR DESCRIPTION
**Pull request by dougsland**

### CODE REVIEW

**Comment by dougsland** [comment]
The job `ci/prow/e2e-handler-ovn-ipv4` is unstable, there a jira card created for fixing it.

**Review by mkowalski — APPROVED** [review]

**Comment by cybertron** [comment]
/retest-required

This is passing for me locally. I'm not sure why CI is having so much trouble with it.

**Comment by mkowalski** [comment]
I had a quick look at must-gather from one of the failing jobs, but the deployment seems to be healthy. Not sure why the test is failing, it seems more about the behaviour and not about the installation process itself (what should be the case if the manifest was wrong)

```
$ o get -n nmstate pod -owide
NAME                                   READY  STATUS   RESTARTS  AGE   IP              NODE
nmstate-cert-manager-5b8d48f489-2jr4r  1/1    Running  0         2h0m  10.128.0.22     master-2
nmstate-handler-p56tz                  1/1    Running  0         2h0m  192.168.111.23  worker-0
nmstate-handler-qw8q7                  1/1    Running  0         2h0m  192.168.111.21  master-1
nmstate-handler-stk8j                  1/1    Running  0         2h0m  192.168.111.22  master-2
nmstate-handler-wtk4n                  1/1    Running  0         2h0m  192.168.111.25  worker-2
nmstate-handler-x7vlk                  1/1    Running  0         2h0m  192.168.111.24  worker-1
nmstate-handler-zfg77                  1/1    Running  0         2h0m  192.168.111.20  master-0
nmstate-operator-7b56456d4-tnc85       1/1    Running  0         2h1m  10.128.0.17     master-2
nmstate-webhook-5b84985d58-fv2mq       1/1    Running  0         2h0m  10.129.0.6      master-0

$ o get -n nmstate deployment
NAME                  READY  UP-TO-DATE  AVAILABLE  AGE
nmstate-cert-manager  1/1    1           1          2h0m
nmstate-operator      1/1    1           1          2h1m
```

**Comment by cybertron** [comment]
/override ci/prow/e2e-handler-sdn-ipv4

We clearly have a CI issue that needs to be resolved, but I don't think we should block 4.13 builds on it. I think this is safe to override for a few reasons:
1) The tests passed for me locally.
2) It's clear from looking at the job history that we've been sitting right around the overall job timeout for a while now. These timed out jobs do not necessarily indicate a problem with the patch.
3) I don't think these manifests affect the behavior of the e2e jobs in a meaningful way. As long as the operator deploys (which it does), the manifests have done their job. Even if individual tests are failing that is not a problem with the manifests.

**Pull request merged**
