### PR TITLE
Rebase to upstream v0.64.0

### PR DESCRIPTION
**Pull request by creydr**
Inspired by the commit description for #227 

Identify carry commits:

```
git remote update
git log --oneline --no-merges v0.64.0..openshift/master
```

Note that the `UPSTREAM: <carry>:` prefix was added to any new commits to carry since the previous rebase. This will make new carry commits easy to identify alongside prior carry commits.

After identifying the carry commits, the next step is to create the new commit-tree that will be used for the rebase and then cherry pick the carry commits into the new branch.

The following commands cover these steps:

Process

```
$ git remote update # make sure we update our refs
$ git checkout v0.64.0 # upstream kubernetes-nmstate 0.64.0 commit tag
$ git checkout -b merge-tmp # create a branch to do our merge work from
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge nmstate/kubernetes-nmstate v0.64.0' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F -
deadbeef12345678 # id of new merge commit, output by the previous command
$ git branch merge-0.64.0 deadbeef12345678 # create a new branch for the cherry-pick work
$ git checkout merge-0.64.0 # make sure we are on the proper branch
$ git cherry-pick <carry commits>
```

* My 0.64.0 merge commit from the above process is (3ec25726).
* With the merge-0.64.0 branch in place, I cherry picked the carry commits since `merge nmstate/kubernetes-nmstate v0.58.0` 620f846a (#227). 
* The `Updating openshift-kubernetes-nmstate-handler images to be consistent with ART Reconciling...` commits were squashed and renamed to `Update Dockerfile images to match ART`
* The following commits were renamed to have the `UPSTREAM: <carry>:` prefix:
  * Remove serviceaccount manifest (6a8abee4)
  * Skip e2e tests which are not supported on OVN (1d01efbe)
* Didn't carry the commit `Cherry-pick: Fix handler e2e test interface cleanups` (9498a6ce), as this was only cherry-picked in #227 and is now included in u/s.

Carried Commits (applied bottom to top / oldest first):

* `UPSTREAM: <carry>: Add midstream approvers and reviewers` (250a7464)
* `UPSTREAM: <carry>: Add manifests for 4.7` (1cbbeb88)
* `UPSTREAM: <carry>: Add manifests for 4.8` (c5c97cef)
* `UPSTREAM: <carry>: Add manifests for 4.9` (5009fcaf)
* `UPSTREAM: <carry>: Add manifests to .PHONY in Makefile ` (d019ad45)
* `UPSTREAM: <carry>: Add ocp-e2e-tests script ` (748d23bd)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (7f8afc16)
* `UPSTREAM: <carry>: Define the suggested namespace for NMState CR ` (ed0b8044)
* `UPSTREAM: <carry>: Add machineconfigs before running e2e tests on OCP ` (458774f7)
* `UPSTREAM: <carry>: update naming convention ` (ddaa44f0)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (441329ce)
* `UPSTREAM: <carry>: Remove serviceaccount manifest ` (6cd500d6)
* `UPSTREAM: <carry>: Provide default NMState CR ` (9608b654)
* `UPSTREAM: <carry>: Skip e2e tests which are not supported on OVN ` (39abea6e)
* `UPSTREAM: <carry>: Add manifests for 4.10 ` (8e2b95cf)
* `UPSTREAM: <carry>: add arm64 to 4.10 CSV ` (c412346f)
* `UPSTREAM: <carry>: Fix JSON error in initialization resource` (a2247a58)

**Release note**:
```release-note
Rebase to nmstate upstream v0.64.0
```

### CODE REVIEW

**Comment by creydr** [comment]
e2e tests with OpenshiftSDN run successfully:

```
...
Ran 60 of 85 Specs in 3476.638 seconds
SUCCESS! -- 60 Passed | 0 Failed | 1 Pending | 24 Skipped
PASS
...
```

**Comment by yboaron** [comment]
> e2e tests with OpenshiftSDN run successfully:
> 
> ```
> ...
> Ran 60 of 85 Specs in 3476.638 seconds
> SUCCESS! -- 60 Passed | 0 Failed | 1 Pending | 24 Skipped
> PASS
> ...
> ```

Cool, tests in latest version include both static route/addresss and DNS

**Comment by creydr** [comment]
> e2e tests with OpenshiftSDN run successfully:
> 
> ```
> ...
> Ran 60 of 85 Specs in 3476.638 seconds
> SUCCESS! -- 60 Passed | 0 Failed | 1 Pending | 24 Skipped
> PASS
> ...
> ```

same for OVN:

```
Ran 54 of 85 Specs in 2637.158 seconds                                                                                                                                                                                                        SUCCESS! -- 54 Passed | 0 Failed | 1 Pending | 30 Skipped                                                                                                                                                                                     PASS
```

**Comment by creydr** [comment]
Closing in favor of #242 (according to https://coreos.slack.com/archives/CP7329Z5Z/p1639383940304600?thread_ts=1639133806.295600&cid=CP7329Z5Z v0.64 had some inconsistent vendoring)

**Pull request closed without merging**
