### PR TITLE
Merge main 2023 02 09 59a7a11e

### PR DESCRIPTION
**Pull request by dougsland**
rebase

### CODE REVIEW

**Comment by cybertron** [comment]
lgtm pending ci passes.

One thing we should look at as a followup is squashing or removing some of these cherry-picks. For example, we don't need both the "tmp: Skip ovs-bridge e2e test with nmstate 1.2" and "Revert "tmp: Skip failing e2e test on OpenShiftSDN"" They're literally a noop at this point. We could squash all the Dockerfile updates too since there's not much point in carrying them all separately.

Let's get this in first though since it looks like a good rebase now.

**Comment by cybertron** [comment]
We know there's a flaky test in the ovn-ipv4 job. If it's just one test that keeps failing I think we can merge this.

**Comment by dougsland** [comment]
> We know there's a flaky test in the ovn-ipv4 job. If it's just one test that keeps failing I think we can merge this.

I believe that's the case.

**Comment by cybertron** [comment]
Looking at the logs I'm not sure about that. The last three were all timeouts after four hours, which is not normal. It looks like there may be a legitimate problem with the tests, based on the logs I'm seeing: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_kubernetes-nmstate/339/pull-ci-openshift-kubernetes-nmstate-master-e2e-handler-ovn-ipv4/1625134609387753472/artifacts/e2e-handler-ovn-ipv4/kubernetes-nmstate-e2e-handler/build-log.txt

**Comment by dougsland** [comment]
> Looking at the logs I'm not sure about that. The last three were all timeouts after four hours, which is not normal. It looks like there may be a legitimate problem with the tests, based on the logs I'm seeing: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_kubernetes-nmstate/339/pull-ci-openshift-kubernetes-nmstate-master-e2e-handler-ovn-ipv4/1625134609387753472/artifacts/e2e-handler-ovn-ipv4/kubernetes-nmstate-e2e-handler/build-log.txt


I still cannot see a problem, it seems random. Yesterday night it was failing `ovn-sdn` test and today it became green. I will give a retest now and tomorrow morning and see what happens. All the rebase patches applied clean, no hacks so far.

**Comment by dougsland** [comment]
Now I see:

```
    "msg": "non-zero return code",[0m
[0;31m    "rc": 1,[0m
[0;31m    "start": "2023-02-14 05:33:51.207137",[0m
[0;31m    "stderr": "error: failed to get pool 'oooq_pool'\nerror: Storage pool not found: no storage pool with matching name 'oooq_pool'",[0m
[0;31m    "stderr_lines": [[0m
[0;31m        "error: failed to get pool 'oooq_pool'",[0m
[0;31m        "error: Storage pool not found: no storage pool with matching name 'oooq_pool'"[0m
[0;31m    ],[0m
```

**Comment by dougsland** [comment]
ci error doesn't seem related to the patch:

```
{  ["e2e-handler-ovn-ipv4" pod "e2e-handler-ovn-ipv4-kubernetes-nmstate-e2e-handler" failed: context canceled
Link to step on registry info site: https://steps.ci.openshift.org/reference/kubernetes-nmstate-e2e-handler
Link to job on registry info site: https://steps.ci.openshift.org/job?org=openshift&repo=kubernetes-nmstate&branch=master&test=e2e-handler-ovn-ipv4, cancelled]}
```

**Comment by cybertron** [comment]
/lgtm

It looks like the OVN job has been broken for a while. Let's get the rebase landed and then we'll investigate what's going wrong.

**Pull request merged**
