### PR TITLE
Rebase to upstream v0.64.1

### PR DESCRIPTION
**Pull request by creydr**
Inspired by the commit description for #227 

Identify carry commits:

```
git remote update
git log --oneline --no-merges v0.64.1..openshift/master
```

Note that the `UPSTREAM: <carry>:` prefix was added to any new commits to carry since the previous rebase. This will make new carry commits easy to identify alongside prior carry commits.

After identifying the carry commits, the next step is to create the new commit-tree that will be used for the rebase and then cherry pick the carry commits into the new branch.

The following commands cover these steps:

Process

```
$ git remote update # make sure we update our refs
$ git checkout v0.64.1 # upstream kubernetes-nmstate 0.64.1 commit tag
$ git checkout -b merge-tmp # create a branch to do our merge work from
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge nmstate/kubernetes-nmstate v0.64.1' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F -
deadbeef12345678 # id of new merge commit, output by the previous command
$ git branch merge-0.64.1 deadbeef12345678 # create a new branch for the cherry-pick work
$ git checkout merge-0.64.1 # make sure we are on the proper branch
$ git cherry-pick <carry commits>
```

* My 0.64.1 merge commit from the above process is (e3768408).
* With the merge-0.64.1 branch in place, I cherry picked the carry commits since `merge nmstate/kubernetes-nmstate v0.58.0` 620f846a (#227). 
* The `Updating openshift-kubernetes-nmstate-handler images to be consistent with ART Reconciling...` commits were squashed and renamed to `Update Dockerfile images to match ART`
* The following commits were renamed to have the `UPSTREAM: <carry>:` prefix:
  * Remove serviceaccount manifest (6a8abee4 -> a051449b)
  * Skip e2e tests which are not supported on OVN (1d01efbe -> 364fe41a)
  * Add ppc64le and s390x to 4.10 CSV (406ed60e -> bb372095)
* Didn't carry the commit `Cherry-pick: Fix handler e2e test interface cleanups` (9498a6ce), as this was only cherry-picked in #227 and is now included in u/s (e02a1981).
* Didn't carry the commit `Add s390x and ppc64le to go install` (7459f1d9), as this referenced an old `install-go.sh` which was removed in b50bbbe5

Carried Commits (applied bottom to top / oldest first):

* `UPSTREAM: <carry>: Add midstream approvers and reviewers` (fa7c3d94)
* `UPSTREAM: <carry>: Add manifests for 4.7` (aa7b0301)
* `UPSTREAM: <carry>: Add manifests for 4.8` (2c3331f4)
* `UPSTREAM: <carry>: Add manifests for 4.9` (85e378bd)
* `UPSTREAM: <carry>: Add manifests to .PHONY in Makefile` (e3bc5855)
* `UPSTREAM: <carry>: Add ocp-e2e-tests script` (b4064beb)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (2581b978)
* `UPSTREAM: <carry>: Define the suggested namespace for NMState CR` (5b1375a5)
* `UPSTREAM: <carry>: Add machineconfigs before running e2e tests on OCP` (b322f05e)
* `UPSTREAM: <carry>: update naming convention` (4f426cd9)
* `UPSTREAM: <carry>: Update dockerfile to match ART` (6a5cb834)
* `UPSTREAM: <carry>: Remove serviceaccount manifest` (a051449b)
* `UPSTREAM: <carry>: Provide default NMState CR` (ab635c05)
* `UPSTREAM: <carry>: Skip e2e tests which are not supported on OVN` (364fe41a)
* `UPSTREAM: <carry>: Add 4.10 release OLM manifests` (809fbb73)
* `UPSTREAM: <carry>: add arm64 to 4.10 CSV` (4a42842e)
* `UPSTREAM: <carry>: Add ppc64le and s390x to 4.10 CSV` (bb372095)
* `UPSTREAM: <carry>: Fix JSON error in initialization resource` (f44af8cd)

**Release note**:
```release-note
Rebase to kubernetes-nmstate upstream v0.64.1
```

### CODE REVIEW

**Comment by creydr** [comment]
Had to rebase again due merge conflicts with merge of #237

**Comment by creydr** [comment]
e2e test on sdn passed again:

```
Ran 60 of 85 Specs in 3475.275 seconds
SUCCESS! -- 60 Passed | 0 Failed | 1 Pending | 24 Skipped
PASS
```

**Comment by cybertron** [comment]
/approve

I had a couple of failures in my local test run, but they were likely flakes. Let's get this in.

**Pull request merged**
