### PR TITLE
OCPBUGS-13014: Skip "with capture" e2e tests on OVNK

### PR DESCRIPTION
**Pull request by cybertron**
Currently the capture tests are not respecting our settings for
secondary interfaces and as a result they try to use the enp2s0
interface in a bond. This won't work since that's the interface
used by configure-ovs, so until we work out a way to make those
tests behave correctly in OVNK clusters we need to skip them in order
to get useful results from the ovn e2e jobs.

**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by cybertron** [comment]
I haven't actually tested this locally yet, but I wanted to let ci chew on it right away in case it does fix the problem.

**Comment by cybertron** [comment]
This passed for me locally. Hopefully it will get the job working again in ci too.

**Comment by cybertron** [comment]
/retest

Failed some build issue.

**Comment by dougsland** [comment]
/lgtm
hope that we addressed the issue.

**Pull request merged**
