### PR TITLE
Rework bundle creation

### PR DESCRIPTION
**Pull request by creydr**
**Is this a BUG FIX or a FEATURE ?**:

/kind enhancement

**What this PR does / why we need it**:
This PR adds new make targets to update the bundle manifests, deploy an operator via its bundle to a cluster and uninstall a bundle:

* `ocp-update-bundle-manifests`: updates the OCP bundle files with its latest changes (e.g. after a rebase)
* `ocp-build-and-deploy-bundle`: builds the bundle and deploys it to an OCP cluster (e.g. via `IMAGE_REPO=creydr KUBECONFIG=~/.kube/config VERSION=2.2.1-tmp make ocp-build-and-deploy-bundle`)
* `ocp-uninstall-bundle`: uninstalls the bundle which got installed via `make ocp-build-and-deploy-bundle`

In addition it adds the `check-ocp-bundle` make target to verify that the bundles are up to date. This can then be run as a required check in CI (https://github.com/openshift/release/pull/30856).

**Special notes for your reviewer**:
* This adds the manifests for 4.12 and cleans up the old manifest files (< 4.12) 
* It aligns the bundle directory with the official suggestion -> we have to adjust https://github.com/openshift/ocp-build-data/blob/openshift-4.11/images/openshift-kubernetes-nmstate-operator.yml#L33-L34 too (done in openshift/ocp-build-data/pull/1792)

**Release note**:
```release-note
none
```

### CODE REVIEW

**Comment by creydr** [comment]
Ready for review as we have openshift/ocp-build-data/pull/1792 in place now too.

/assign @cybertron 
/hold to go in with the same tide as openshift/ocp-build-data/pull/1792

**Comment by creydr** [comment]
@cybertron could you PTAL? This makes it easier for us to test changes on the operator and is some kind of prerequisite to add e2e tests against the bundle.

**Comment by cybertron** [comment]
I tried this out locally but the first yq is failing:

> yq --inplace eval '.spec.install.spec.clusterPermissions[] |= select(.rules[]) |= select(.serviceAccountName == "nmstate-operator").rules += {"apiGroups":["security.openshift.io"],"resources":["securitycontextconstraints"],"verbs":["use"],"resourceNames":["privileged"]}' manifests/4.12/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
usage: yq [-h] [--yaml-output] [--yaml-roundtrip] [--width WIDTH] [--indentless-lists] [--in-place] [--version] [jq_filter] [files ...]
yq: error: argument files: can't open '.spec.install.spec.clusterPermissions[] |= select(.rules[]) |= select(.serviceAccountName == "nmstate-operator").rules += {"apiGroups":["security.openshift.io"],"resources":["securitycontextconstraints"],"verbs":["use"],"resourceNames":["privileged"]}': [Errno 2] No such file or directory: '.spec.install.spec.clusterPermissions[] |= select(.rules[]) |= select(.serviceAccountName == "nmstate-operator").rules += {"apiGroups":["security.openshift.io"],"resources":["securitycontextconstraints"],"verbs":["use"],"resourceNames":["privileged"]}'
make: *** [Makefile:242: ocp-update-bundle-manifests] Error 2

I tried fiddling with it a bit, but I never got it to work. I did notice that yq on my system does not have --inplace, it has --in-place. It also required -y.

I'm wondering if we have different yq versions. I was on 2.12 and updated to 3.1.0 to see if it would help, but it behaves the same.

**Comment by creydr** [comment]
> I tried this out locally but the first yq is failing:
> 
> > yq --inplace eval '.spec.install.spec.clusterPermissions[] |= select(.rules[]) |= select(.serviceAccountName == "nmstate-operator").rules += {"apiGroups":["security.openshift.io"],"resources":["securitycontextconstraints"],"verbs":["use"],"resourceNames":["privileged"]}' manifests/4.12/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
> > usage: yq [-h] [--yaml-output] [--yaml-roundtrip] [--width WIDTH] [--indentless-lists] [--in-place] [--version] [jq_filter] [files ...]
> > yq: error: argument files: can't open '.spec.install.spec.clusterPermissions[] |= select(.rules[]) |= select(.serviceAccountName == "nmstate-operator").rules += {"apiGroups":["security.openshift.io"],"resources":["securitycontextconstraints"],"verbs":["use"],"resourceNames":["privileged"]}': [Errno 2] No such file or directory: '.spec.install.spec.clusterPermissions[] |= select(.rules[]) |= select(.serviceAccountName == "nmstate-operator").rules += {"apiGroups":["security.openshift.io"],"resources":["securitycontextconstraints"],"verbs":["use"],"resourceNames":["privileged"]}'
> > make: *** [Makefile:242: ocp-update-bundle-manifests] Error 2
> 
> I tried fiddling with it a bit, but I never got it to work. I did notice that yq on my system does not have --inplace, it has --in-place. It also required -y.
> 
> I'm wondering if we have different yq versions. I was on 2.12 and updated to 3.1.0 to see if it would help, but it behaves the same.

Good catch. I have yq v4.x on my system. I added 54065f4 which addresses this and uses a yq v4 binary in case yq != v4 is installed on the system.

**Comment by creydr** [comment]
@cybertron would be great if you could have a look at this PR

**Comment by creydr** [comment]
> Okay, the yq problem is fixed, but my deployment is still failing:
> 
> ```
> conditions:
>   - lastTransitionTime: "2022-08-17T20:03:17Z"
>     message: all available catalogsources are healthy
>     reason: AllCatalogSourcesHealthy
>     status: "False"
>     type: CatalogSourcesUnhealthy
>   - message: 'constraints not satisfiable: subscription kubernetes-nmstate-operator
>       requires kubernetes-nmstate-catalog/openshift-marketplace/4.12/kubernetes-nmstate-operator.v4.12.0,
>       subscription kubernetes-nmstate-operator exists, clusterserviceversion kubernetes-nmstate-operator.v4.12.0
>       exists and is not referenced by a subscription, @existing/openshift-nmstate//kubernetes-nmstate-operator.v4.12.0
>       and kubernetes-nmstate-catalog/openshift-marketplace/4.12/kubernetes-nmstate-operator.v4.12.0
>       originate from package kubernetes-nmstate-operator'
>     reason: ConstraintsNotSatisfiable
>     status: "True"
>     type: ResolutionFailed
> ```
> 
> I'm having a bit of difficulty parsing out what the actual problem here is. :-/

IIRC I had this issue at the beginning, when another nmstate operator was already installed. I updated the "uninstall" script to check for the CSV too. In addition it seems it had an issue with 4.12 (when I checked it a few days ago it seems 4.11 was still the default). I had to update OPM (da609f9f5a8a0a4af127fc2364ac67cc519e9864)...

**Comment by cybertron** [comment]
> IIRC I had this issue at the beginning, when another nmstate operator was already installed. I updated the "uninstall" script to check for the CSV too. In addition it seems it had an issue with 4.12 (when I checked it a few days ago it seems 4.11 was still the default). I had to update OPM ([da609f9](https://github.com/openshift/kubernetes-nmstate/commit/da609f9f5a8a0a4af127fc2364ac67cc519e9864))...

Ah, probably related to a previously failed attempt then. I had a permission problem on my quay repos the first time I tried it.

It's working for me now, so looks good to go. Need to figure out if this or https://github.com/openshift/ocp-build-data/pull/1792 need to merge first.

/lgtm

**Comment by creydr** [comment]
> It's working for me now, so looks good to go. Need to figure out if this or [openshift/ocp-build-data#1792](https://github.com/openshift/ocp-build-data/pull/1792) need to merge first.

openshift/ocp-build-data/pull/1792 got lgtm'ed. So we should be OK to remove the hold on both and get this in for 4.12

/hold cancel

**Pull request merged**
