### PR TITLE
[release-4.8] Bug 2095360: Add e2e test scripts

### PR DESCRIPTION
**Pull request by creydr**
**Is this a BUG FIX or a FEATURE ?**:

**What this PR does / why we need it**:
Cherry-picks the commits to run the e2e tests.

**Special notes for your reviewer**:
Had to cherry-pick some commits from u/s which were not included in 0.47 and prefixed them with `UPSTREAM: <carry>: <cherry-pick`:
* e02a198169554080ffabc982c14533e652b969c3
* eb4cfb6a88b9cd0c9fe04ef75b5dd445b8de4138
* 322cf1f587f66b89cefa24a8c8b6738b5375aac1
* 1d01efbee52f31d740a39a6cbe647f6b3e39226f
* 4fe0d7a1f8e74cab91a5e4dfa74e60f052cc90bb

**Release note**:
```release-note
Added e2e test setup
```

/hold until I got the test results

### CODE REVIEW

**Comment by cybertron** [comment]
/lgtm
/approve

We'll need to wait on Christoph's testing and QE verifying the 4.9 bug, but once those things happen this should be fine to go in.

**Comment by creydr** [comment]
Running them locally:
```
Ran 34 of 54 Specs in 2350.824 seconds
SUCCESS! -- 34 Passed | 0 Failed | 0 Flaked | 2 Pending | 18 Skipped
PASS
```

**Pull request merged**
