### PR TITLE
OCPBUGS-11347: Merge main 2023 04 14 1b33f6e7

### PR DESCRIPTION
**Pull request by cybertron**
**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by cybertron** [comment]
This may also fix OCPBUGS-11733. If CI passes I'll add that reference.

**Comment by dougsland** [comment]
LGTM but seems need to update manifest
```
+ echo 'It seems like you need to run '\''make ocp-update-bundle-manifests'\''. Please run it and commit the changes'
It seems like you need to run 'make ocp-update-bundle-manifests'. Please run it and commit the changes
+ git status --porcelain
 M manifests/stable/manifests/nmstate.io_nmstates.yaml
```

**Comment by cybertron** [comment]
We need a different rebase patch now.

**Pull request closed without merging**
