### PR TITLE
update naming convention

### PR DESCRIPTION
**Pull request by Ximinhan**
align the correct image name

**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What this PR does / why we need it**:
currently the image name is kubernetes-nmstate-operator
**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Ximinhan** [comment]
Hi @rhrazdil  thanks for review, is this fix pr will fast-forward to separate release branch so I can close the similar pr for release-4.9 branch?

**Comment by rhrazdil** [comment]
@Ximinhan Hi, I don't know, I'm mostly working on u/s nmstate/kubernetes-nmstate repository

**Comment by Ximinhan** [comment]
@rhrazdil got it, so I will keep the pr https://github.com/openshift/kubernetes-nmstate/pull/222 , please approve both

**Review by rhrazdil — APPROVED** [review]
/approve

**Pull request merged**
