### PR TITLE
OCPBUGS-7328: Grant handler service account permissions to use privileged security context constraint on OCP/OKD

### PR DESCRIPTION
**Pull request by mkowalski**
Use non cached client for operators node actions
    
(cherry-picked from commit 377fa5485b157eb381fbe5e6c4769aa981ffabbc)
(cherry-picked from nmstate/kubernetes-nmstate/pull/1102)

---

* Grant handler SA permissions to use privileged security context constraint on OCP or OKD
* Fix typo

(cherry-picked from commit 2e8c06a8b3ff8743820dd77866b0dc7005914262)
(cherry-picked from nmstate/kubernetes-nmstate/pull/1113)

---

UPSTREAM: <carry>: Remove handler SA permissions from CSV

Since 2e8c06a8b3ff8743820dd77866b0dc7005914262 the permissions for the
handler service account are all defined in the operator code, so there
is no need anymore to define OpenShift specific permissions in the CSV
or for e2e tests anymore.

(cherry-picked from 0412ecb143059f2fcf494ce8d3c97ebc31a4607f)

### CODE REVIEW

**Comment by mkowalski** [comment]
/hold

That seems like a valid failure
```
 go run hack/render-manifests.go -handler-prefix= -handler-namespace=nmstate -operator-namespace=nmstate -handler-image=registry.build05.ci.openshift.org/ci-op-rn5y79gw/pipeline@sha256:8b9097d4d99ac2bebdb1519e707b7908641bfcdfc33b55c7125d48657e9c1818 -operator-image=registry.build05.ci.openshift.org/ci-op-rn5y79gw/pipeline@sha256:589779511700b8c3b938087cbaeacbc22cfccc4ff286352d9b63a96ed128a0fa -handler-pull-policy=Always -operator-pull-policy=Always -input-dir=deploy/ -output-dir=build/_output/manifests
KUBECONFIG=/tmp/secret/kubeconfig OPERATOR_NAMESPACE=nmstate go run github.com/onsi/ginkgo/v2/ginkgo -v -timeout=80m --slow-spec-threshold=60s  ./test/e2e/operator ...
Failed to compile operator:
# k8s.io/cli-runtime/pkg/resource
../../../vendor/k8s.io/cli-runtime/pkg/resource/metadata_decoder.go:27:33: undefined: "k8s.io/apimachinery/pkg/runtime/serializer/json".CaseSensitiveJSONIterator 
```

**Review by dougsland — COMMENTED** [review]
/lgtm

**Pull request merged**
