### PR TITLE
[4.13] handler: Retry enactment update

### PR DESCRIPTION
**Pull request by mkowalski**

### CODE REVIEW

**Comment by mkowalski** [comment]
/hold

It may be that this never passes

**Comment by cybertron** [comment]
/hold cancel
4.14 is in

**Comment by mkowalski** [comment]
/test check-generate-bundle

LOL, what is that even
```
 + git checkout bundle.Dockerfile
fatal: detected dubious ownership in repository at '/go/src/github.com/openshift/kubernetes-nmstate'
To add an exception for this directory, call:
	git config --global --add safe.directory /go/src/github.com/openshift/kubernetes-nmstate
make: *** [Makefile:241: ocp-update-bundle-manifests] Error 128 
```

**Comment by mkowalski** [comment]
/hold

CI regressed when upgrading git. Master already fixed (https://github.com/openshift-eng/ocp-build-data/pull/4257), backports will follow

**Pull request merged**
