### PR TITLE
[4.14] handler: Retry enactment update

### PR DESCRIPTION
**Pull request by mkowalski**

### CODE REVIEW

**Comment by mkowalski** [comment]
/hold

It may be that this never passes

**Comment by cybertron** [comment]
/lgtm

OVN job passed, so it's unlikely the SDN failure is anything but a flake.

**Comment by mkowalski** [comment]
/test e2e-handler-sdn-ipv4

Has this ever worked...?

**Comment by cybertron** [comment]
Weird. It's usually the ovn job that is unstable. :-) This is failing consistently on the same test, so I think there may be a legitimate problem here. I pushed a test PR at https://github.com/openshift/kubernetes-nmstate/pull/458 to confirm that this is unrelated to the change (which I think it is since it looks like this also failed on the snyk change that had no functional impact).

**Comment by qinqon** [comment]
Looks like is failing on the dns resolver tests 

```

[38;5;9m[1mSummarizing 1 Failure:[0m
  [38;5;9m[FAIL][0m [0mrollback [38;5;243mwhen name servers are wrong after state configuration [38;5;9m[1m[It] should rollback to previous name servers[0m
  [38;5;243m/go/src/github.com/openshift/kubernetes-nmstate/test/e2e/policy/conditions.go:196[0m

```

**Pull request merged**
