### PR TITLE
[release-4.8] Bug 2092355: Rebase to 0.47.11

### PR DESCRIPTION
**Pull request by creydr**
Inspired by the commit description for #243 

Identify carry commits:

```
git remote update
git log --oneline --no-merges v0.47.11..openshift/release-4.8
```

Note that the `UPSTREAM: <carry>:` prefix was added to any new commits to carry since the previous rebase. This will make new carry commits easy to identify alongside prior carry commits.

After identifying the carry commits, the next step is to create the new commit-tree that will be used for the rebase and then cherry pick the carry commits into the new branch.

The following commands cover these steps:

Process

```
$ git remote update # make sure we update our refs
$ git checkout v0.47.11 # upstream kubernetes-nmstate 0.47.11 commit tag
$ git checkout -b merge-tmp # create a branch to do our merge work from
$ git checkout openshift/release-4.8 # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge nmstate/kubernetes-nmstate v0.47.11' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F -
deadbeef12345678 # id of new merge commit, output by the previous command
$ git branch merge-0.47.11 deadbeef12345678 # create a new branch for the cherry-pick work
$ git checkout merge-0.47.11 # make sure we are on the proper branch
$ git cherry-pick <carry commits>
```

* My 0.47.11 merge commit from the above process is (2f5ff1ef6).
* With the merge-0.47.11 branch in place, I cherry picked the carry commits since `merge nmstate/kubernetes-nmstate v0.47.0` af57ae1ea (#191). 

Carried Commits:

* `UPSTREAM: <carry>: Add midstream approvers and reviewers` (623a6ef80)
* `UPSTREAM: <carry>: Add manifests for 4.7` (0cfa30e91)
* `UPSTREAM: <carry>: Add manifests for 4.8` (16dc2362c)
* `UPSTREAM: <carry>: Change handler toleration to "operator: exists" (#755)` (974af0366)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (340e7fb41)
* `UPSTREAM: <carry>: Set default bundle channel to 4.8` (faff31604)
* `UPSTREAM: <carry>: Name replacement must exactly match string in CSV` (f1e666408)
* `UPSTREAM: <carry>: Fix olm.skipRange substitution` (62ae1127a)
* `UPSTREAM: <carry>: Remove serviceaccount manifest` (66048b5ac)

**Release note**:
```release-note
Rebase to kubernetes-nmstate upstream v0.47.11
```

### CODE REVIEW

**Comment by creydr** [comment]
@cybertron @phoracek @qinqon the e2e tests passed after the rebase. Do we have a BZ for this?

**Comment by cybertron** [comment]
Yes: https://bugzilla.redhat.com/show_bug.cgi?id=2092355

**Pull request merged**
