### PR TITLE
Bug 2046191: Add qos class and priority class to operator template in CSV

### PR DESCRIPTION
**Pull request by creydr**
**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What this PR does / why we need it**:
Need to add the qos class and priority class to the template of the operator in the CSV file.

**Release note**:
```release-note
none
```

### CODE REVIEW

**Comment by cybertron** [comment]
/hold

Forgot the e2e jobs aren't required. Let's make sure it passes before we merge this.

**Comment by creydr** [comment]
tests passed
/unhold

**Pull request merged**
