### PR TITLE
[DownstreamMerge] Rebase to upstream/main (2022-09-20)

### PR DESCRIPTION
**Pull request by creydr**
Rebased to latest upstream/main to get fe6b98c020989a09240816c7a7db49362e0fd338 which is required for an nmstate fix ([BZ 2111945](https://bugzilla.redhat.com/show_bug.cgi?id=2111945)).

I created a script to do the rebase, which I will add in another PR (#301).

Cherry-picked commit since (8e7127cb672ba84f5fa876590c1696e8c3bf0623)
New merge commit is `merge nmstate/main 2022-09-20 (38daf048c4d4decab561b287a5ceccd2ab995b1d)`

**Cherry-picked/carried commits:**
* `UPSTREAM: <carry>: Add midstream approvers and reviewers` (0d1778abf)
* `UPSTREAM: <carry>: Add manifests for 4.7` (b430df3be)
* `UPSTREAM: <carry>: Add manifests for 4.8` (aa087f9d1)
* `UPSTREAM: <carry>: Add manifests for 4.9` (6691f5c78)
* `UPSTREAM: <carry>: Add manifests to .PHONY in Makefile` (8710bef3b)
* `UPSTREAM: <carry>: Add ocp-e2e-tests script` (c85163525)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (bae372064)
* `UPSTREAM: <carry>: Define the suggested namespace for NMState CR` (b15613f07)
* `UPSTREAM: <carry>: Add machineconfigs before running e2e tests on OCP` (7b97ef5f7)
* `UPSTREAM: <carry>: update naming convention` (ea9ce10fb)
* `UPSTREAM: <carry>: Update dockerfile to match ART` (3cd86d38b)
* `UPSTREAM: <carry>: Remove serviceaccount manifest` (c49085e8a)
* `UPSTREAM: <carry>: Provide default NMState CR` (57ac5d799)
* `UPSTREAM: <carry>: Skip e2e tests which are not supported on OVN` (12054ceb7)
* `UPSTREAM: <carry>: Add 4.10 release OLM manifests` (9e70208cb)
* `UPSTREAM: <carry>: add arm64 to 4.10 CSV` (b7bec0488)
* `UPSTREAM: <carry>: Add ppc64le and s390x to 4.10 CSV` (8304a417d)
* `UPSTREAM: <carry>: Fix JSON error in initialization resource` (866521351)
* `UPSTREAM: <carry>: Update OWNERS` (e22a51ce8)
* `UPSTREAM: <carry>: Switch to dnf in Openshift handler image` (3af5b7c62)
* `UPSTREAM: <carry>: Add disconnected annotation for OperatorHub` (c3a2a174b)
* `UPSTREAM: <carry>: enable all archs in nmstate example CR` (dd858b11a)
* `UPSTREAM: <carry>: Add ssh proxy for e2e tests in CI` (05e992d19)
* `UPSTREAM: <carry>: Remove initialization resource from CSV` (1724a9b95)
* `UPSTREAM: <carry>: Apply SCC in e2e tests when reinstalling operator in another namespace` (fb7435019)
* `UPSTREAM: <carry>: Add make target to run operator e2e tests against ocp` (87cce8c6e)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (34a364819)
* `UPSTREAM: <carry>: Add operators app label in CSV` (f2bf050fa)
* `UPSTREAM: <carry>: Do not ignore parameters for ocp tests` (ea1dff509)
* `UPSTREAM: <carry>: Add manifests for 4.11` (62107339d)
* `UPSTREAM: <carry>: Fix ssh-ci.sh for dualstack environments` (e5fe706e5)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (e7e4e0fed)
* `UPSTREAM: <carry>: Add qosClass to operator CSV` (5ec849b1d)
* `UPSTREAM: <carry>: add priority class to operator CSV` (4b0aaa5f9)
* `UPSTREAM: <carry>: Rerun flaky e2e tests` (89d0f12b7)
* `UPSTREAM: <carry>: Update 4.11 CSV file after rebase` (c05f5ca0c)
* `UPSTREAM: <carry>: Update NMState CRD` (87e52cfa2)
* `UPSTREAM: <carry>: Set SSH env correctly for operator e2e tests` (c5e879ff7)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (d112e9a12)
* `UPSTREAM: <carry>: Update CSV after rebase` (dd971166b)
* `tmp: Skip failing e2e test on OpenShiftSDN` (8f0fd5bb0)
* `UPSTREAM: <carry>: Fix OLM skipRange replacement` (8bfcde1fc)
* `UPSTREAM: <carry>: Remove old manifests` (0d1908401)
* `UPSTREAM: <carry>: Rename deprecated flakeAttempts parameter` (0e698dfe0)
* `UPSTREAM: <carry>: Timeout handler e2e tests after 4h` (bcb773b5d)
* `UPSTREAM: <carry>: Add make target to update bundle manifests and install bundle` (f909784da)
* `UPSTREAM: <carry>: Add check to verify bundles have been updated` (60213aa8f)
* `UPSTREAM: <carry>: Add manifests for 4.12` (6b7c088dd)
* `UPSTREAM: <carry>: Make sure yq v4 is installed for bundle updates` (bacb24e56)
* `UPSTREAM: <carry>: Update OPM for 4.12` (7eb76221b)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (654863842)
* `UPSTREAM: <carry>: Update bundle manifests after rebase` (f1c24aca2)
* `UPSTREAM: <carry>: Remove handler SA permissions from CSV` (d4593c632)
* `tmp: Skip ovs-bridge e2e test with nmstate 1.2` (97f52d42f)

### CODE REVIEW

**Comment by cybertron** [comment]
/lgtm
/hold

We know the ovn handler job has a flake so I'm not concerned about that. Once we get a pass this should be good to go.

**Comment by creydr** [comment]
@cybertron: I added 6c258a6 to skip the irrelevant LLDP tests on OVN.

**Comment by dougsland** [comment]
just waiting the last job be done before the lgtm

**Comment by creydr** [comment]
> @creydr: all tests **passed!**
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openshift&repo=kubernetes-nmstate&pr=300). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:creydr).

/hold cancel
@cybertron @dougsland the tests passed. Could you recheck?

**Pull request merged**
