### PR TITLE
Make downstream build (monitoring fixes)

### PR DESCRIPTION
**Pull request by mkowalski**
Multiple commits to fix upstream issues that prevent from building downstream. Look at "commits" tab for detailed descriptions.

### CODE REVIEW

**Comment by qinqon** [comment]
I reproduce the generate bundle issue upstream  `make bundle`
```
HEAD is now at df565dd7b operator: configurable placeholder for kube-rbac-proxy (#1245)
[ellorent@fedora kubernetes-nmstate]$ make bundle 
cd api && GOFLAGS=-mod=mod go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.8.0 crd paths="./..." output:crd:artifacts:config=../deploy/crds
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0c06f]

goroutine 114 [running]:
go/types.(*Checker).handleBailout(0xc000330400, 0xc001a8bd40)
	/home/ellorent/.gvm/gos/go1.22.3/src/go/types/check.go:367 +0x88
panic({0xbb8e00?, 0x129ed30?})
	/home/ellorent/.gvm/gos/go1.22.3/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xdad598, 0x12a7760})
	/home/ellorent/.gvm/gos/go1.22.3/src/go/types/sizes.go:228 +0x30f
go/types.(*Config).sizeof(...)
	/home/ellorent/.gvm/gos/go1.22.3/src/go/types/sizes.go:333
go/types.representableConst.func1({0xdad598?, 0x12a7760?})
	/home/ellorent/.gvm/gos/go1.22.3/src/go/types/const.go:76 +0x9e
go/types.representableConst({0xdb3a60, 0x12735e0}, 0xc000330400, 0x12a7760, 0xc001a8b4b0)
	/home/ellorent/.gvm/gos/go1.22.3/src/go/types/const.go:92 +0x192

```

**Review by cybertron — COMMENTED** [review]
/lgtm

**Comment by mkowalski** [comment]
Framework issue? Cannot connect to the host in the handler job -- https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_kubernetes-nmstate/487/pull-ci-openshift-kubernetes-nmstate-master-e2e-handler-ovn-ipv4/1800273826920009728/artifacts/e2e-handler-ovn-ipv4/kubernetes-nmstate-e2e-handler/build-log.txt

Anyway overriding this as this needs manual love

/override ci/prow/e2e-handler-ovn-ipv4

**Pull request merged**
