### PR TITLE
[4.12] handler: Retry enactment update

### PR DESCRIPTION
**Pull request by mkowalski**

### CODE REVIEW

**Comment by cybertron** [comment]
/approve
/hold

Once 4.13 merges this can go in.

**Comment by mkowalski** [comment]
/override ci/prow/e2e-handler-sdn-ipv4

This job fails on the clean branch too. We fill fix that as part of another effort, but this PR can roll anyway

**Comment by mkowalski** [comment]
@cybertron can you try to override? For some strange reason I cannot...

**Comment by mkowalski** [comment]
/test e2e-handler-sdn-ipv4

The pending stuff is somehow related to the DNS, but not sure if that's not a false flag

```
[38;5;11mP [PENDING][0m
[0mDns configuration [38;5;243mwhen desiredState is configured [0mwith DHCP unaware interface, Skip Reason: https://bugzilla.redhat.com/show_bug.cgi?id=2054726 [38;5;243mwith V4 upstream servers [0mshould have the static V4 address[0m
[38;5;243m/go/src/github.com/openshift/kubernetes-nmstate/test/e2e/handler/dns_test.go:265[0m
[38;5;243m------------------------------[0m
[38;5;11mP [PENDING][0m
[0mDns configuration [38;5;243mwhen desiredState is configured [0mwith DHCP unaware interface, Skip Reason: https://bugzilla.redhat.com/show_bug.cgi?id=2054726 [38;5;243mwith V6 upstream servers [0mshould have the static V6 address[0m
[38;5;243m/go/src/github.com/openshift/kubernetes-nmstate/test/e2e/handler/dns_test.go:294[0m
```

**Comment by cybertron** [comment]
> @cybertron can you try to override? For some strange reason I cannot...

Probably because you weren't in the OWNERS file in 4.12. If this PR is failing the same way as a noop I'm happy to override it (assuming it fails again).

**Comment by mkowalski** [comment]
Yes, this one here hangs on

1) `[0mDns configuration [38;5;243mwhen desiredState is configured [0mwith DHCP unaware interface, Skip Reason: https://bugzilla.redhat.com/show_bug.cgi?id=2054726 [38;5;243mwith V4 upstream servers [0mshould have the static V4 address[0m`
2) `[0mDns configuration [38;5;243mwhen desiredState is configured [0mwith DHCP unaware interface, Skip Reason: https://bugzilla.redhat.com/show_bug.cgi?id=2054726 [38;5;243mwith V6 upstream servers [0mshould have the static V6 address[0m`

whereas no-op fails on 

1) `[0mDns configuration [38;5;243mwhen desiredState is configured [0mwith DHCP unaware interface, Skip Reason: https://bugzilla.redhat.com/show_bug.cgi?id=2054726 [38;5;243mwith V4 upstream servers [0mshould have the static V4 address[0m`
2) `[0mDns configuration [38;5;243mwhen desiredState is configured [0mwith DHCP unaware interface, Skip Reason: https://bugzilla.redhat.com/show_bug.cgi?id=2054726 [38;5;243mwith V6 upstream servers [0mshould have the static V6 address[0m`

and additionally fails on

1) `   when name servers are wrong after state configuration
  /go/src/github.com/openshift/kubernetes-nmstate/test/e2e/handler/rollback_test.go:201
    [It] should rollback to previous name servers `

So this PR fixed one failure and did not change the state of 2 hanging tests

**Comment by cybertron** [comment]
/override ci/prow/e2e-handler-sdn-ipv4

We know the failing tests are failing on noop changes too, so let's get this bug fix in while we investigate the unrelated test failures.

**Pull request merged**
