### PR TITLE
metrics: DISABLE the feature for 4.16

### PR DESCRIPTION
**Pull request by mkowalski**

### CODE REVIEW

**Comment by mkowalski** [comment]
/retest

One failure with infra setup. One failure may be a valid error

```
 Summarizing 5 Failures:
  [FAIL] NMState operator for control-plane size [It] of two nodes should deploy webhook replicas at different nodes
  /go/src/github.com/openshift/kubernetes-nmstate/test/e2e/operator/operator.go:154
  [FAIL] NMState operator when installed for the first time [It] should deploy a ready operand
  /go/src/github.com/openshift/kubernetes-nmstate/test/e2e/operator/operator.go:154
  [FAIL] NMState operator when installed for the first time and another CR is created with different name [BeforeEach] should remove NMState with different name
  /go/src/github.com/openshift/kubernetes-nmstate/test/e2e/operator/operator.go:154
  [FAIL] NMState operator when installed for the first time and another handler is installed with different namespace [BeforeEach] should wait for defaultOperator handler to be deleted before deploying new altOperator handler
  /go/src/github.com/openshift/kubernetes-nmstate/test/e2e/operator/operator.go:154
  [FAIL] NMState operator when cluser-reader exists [BeforeEach] should be able to read NMState resources with cluster-reader user
  /go/src/github.com/openshift/kubernetes-nmstate/test/e2e/operator/operator.go:154 
```

**Comment by mkowalski** [comment]
/retest

The only failure does not look related to metrics

```
 Summarizing 1 Failure:
  [FAIL] [nns] NNS OVN bridge mappings [BeforeEach] are listed
  /go/src/github.com/openshift/kubernetes-nmstate/test/e2e/handler/nns_ovn.go:39 
```

**Review by cybertron — COMMENTED** [review]
/lgtm

**Comment by mkowalski** [comment]
/override ci/prow/e2e-handler-ovn-ipv4

We have the same test failing on master and it's the only one test that fails. When we fix it on master, we will know what to backport. But now we need to move forward with 4.16

**Pull request merged**
