### PR TITLE
OCPBUGS-7135: Grant handler service account permissions to use privileged security context constraint on OCP/OKD

### PR DESCRIPTION
**Pull request by mkowalski**
Use non cached client for operators node actions
    
(cherry-picked from commit 377fa5485b157eb381fbe5e6c4769aa981ffabbc)
(cherry-picked from nmstate/kubernetes-nmstate/pull/1102)

---

* Grant handler SA permissions to use privileged security context constraint on OCP or OKD
* Fix typo

(cherry-picked from commit 2e8c06a8b3ff8743820dd77866b0dc7005914262)
(cherry-picked from nmstate/kubernetes-nmstate/pull/1113)

---

UPSTREAM: <carry>: Remove handler SA permissions from CSV

Since 2e8c06a8b3ff8743820dd77866b0dc7005914262 the permissions for the
handler service account are all defined in the operator code, so there
is no need anymore to define OpenShift specific permissions in the CSV
or for e2e tests anymore.

(cherry-picked from 0412ecb143059f2fcf494ce8d3c97ebc31a4607f)

### CODE REVIEW

**Comment by mkowalski** [comment]
Only conflicting files
* go.mod
* go.sum
* vendor/modules.txt

Fixed those manually

**Comment by cybertron** [comment]
< error: the path "build/_output/manifests/scc.yaml" does not exist

Looks like there's a problem. Maybe there was another patch in 4.12 that made it work with this change?

**Comment by mkowalski** [comment]
/test e2e-handler-sdn-ipv4

Doesn't seem like our failure. The cluster was almost ready
```
 level=debug msg=Still waiting for the cluster to initialize: Working towards 4.11.0-0.ci.test-2023-02-10-094326-ci-op-5hqxpxfj-latest: 781 of 805 done (97% complete) 
```

**Pull request merged**
