### PR TITLE
[release-4.10] Bug 2059095: Rebase to upstream v0.64.7

### PR DESCRIPTION
**Pull request by creydr**
In the 4.10 branch, we are currently based on v0.64.1. This PR rebases to 0.64.7 to get the latest patches.

Inspired by the commit description for #243 

Identify carry commits:

```
git remote update
git log --oneline --no-merges v0.64.7..openshift/release-4.10
```

Note that the `UPSTREAM: <carry>:` prefix was added to any new commits to carry since the previous rebase. This will make new carry commits easy to identify alongside prior carry commits.

After identifying the carry commits, the next step is to create the new commit-tree that will be used for the rebase and then cherry pick the carry commits into the new branch.

The following commands cover these steps:

Process

```
$ git remote update # make sure we update our refs
$ git checkout v0.64.7 # upstream kubernetes-nmstate 0.64.7 commit tag
$ git checkout -b merge-tmp # create a branch to do our merge work from
$ git checkout openshift/release-4.10 # we want to be at the tip of the openshift release-4.10 branch when we run the next command
$ echo 'merge nmstate/kubernetes-nmstate v0.64.7' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F -
deadbeef12345678 # id of new merge commit, output by the previous command
$ git branch merge-0.64.7 deadbeef12345678 # create a new branch for the cherry-pick work
$ git checkout merge-0.64.7 # make sure we are on the proper branch
$ git cherry-pick <carry commits>
```

* My 0.64.7 merge commit from the above process is (8db16575b).
* With the merge-0.64.7 branch in place, I cherry picked the carry commits since `merge nmstate/kubernetes-nmstate v0.64.1` e37684083 (#243). 
* The commits `Remove initialization resource from CSV` (cccc287de) and `Remove initialization resource from 4.9 too` (4e1f7f6ef) were squashed into 6778bf192 and prefixed with `UPSTREAM: <carry>:`

Carried Commits (applied bottom to top / oldest first):

* `UPSTREAM: <carry>: Add midstream approvers and reviewers` (ec788a5e2)
* `UPSTREAM: <carry>: Add manifests for 4.7` (556078c0e)
* `UPSTREAM: <carry>: Add manifests for 4.8` (c51e749a8)
* `UPSTREAM: <carry>: Add manifests for 4.9` (fa431d509)
* `UPSTREAM: <carry>: Add manifests to .PHONY in Makefile` (1dbccf3e5)
* `UPSTREAM: <carry>: Add ocp-e2e-tests script` (a433ab908)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (0e5c3691f)
* `UPSTREAM: <carry>: Define the suggested namespace for NMState CR` (2f17fe2e7)
* `UPSTREAM: <carry>: Add machineconfigs before running e2e tests on OCP` (8facb7ada)
* `UPSTREAM: <carry>: update naming convention` (a2ab5da5c)
* `UPSTREAM: <carry>: Update dockerfile to match ART` (9a05b6d48)
* `UPSTREAM: <carry>: Remove serviceaccount manifest` (2da846835)
* `UPSTREAM: <carry>: Provide default NMState CR` (862a87c87)
* `UPSTREAM: <carry>: Skip e2e tests which are not supported on OVN` (aac405e2b)
* `UPSTREAM: <carry>: Add 4.10 release OLM manifests` (7ee949018)
* `UPSTREAM: <carry>: add arm64 to 4.10 CSV` (f1103d325)
* `UPSTREAM: <carry>: Add ppc64le and s390x to 4.10 CSV` (d19fb05b5)
* `UPSTREAM: <carry>: Update OWNERS` (930b6f1be)
* `UPSTREAM: <carry>: Fix JSON error in initialization resource` (9620d7d28)
* `UPSTREAM: <carry>: Switch to dnf in Openshift handler image` (35886e5f3)
* `UPSTREAM: <carry>: Add disconnected annotation for OperatorHub` (2e5fc7d0a)
* `UPSTREAM: <carry>: enable all archs in nmstate example CR` (295921cc6)
* `UPSTREAM: <carry>: Add ssh proxy for e2e tests in CI` (1587cfd87)
* `UPSTREAM: <carry>: Remove initialization resource from CSV` (6778bf192)
* `UPSTREAM: <carry>: Apply SCC in e2e tests when reinstalling operator in another namespace` (75105462e)
* `UPSTREAM: <carry>: Add make target to run operator e2e tests against ocp` (ba77f53e4)
* `UPSTREAM: <carry>: Add operators app label in CSV` (e4feb950f)

**Release note**:
```release-note
Rebase to kubernetes-nmstate upstream v0.64.7
```

Including fixes:
* 5ab935fb03628fdc17f68f3d56a5f0458a5f38f2 fixes [BZ 2059095](https://bugzilla.redhat.com/show_bug.cgi?id=2059095)
* e59fc558393e0c155cc780c2892a109acc32a2a9 fixes [BZ 2053491](https://bugzilla.redhat.com/show_bug.cgi?id=2053491)
* b40ec5ef37ac4acf61d818514e0b485f1ce10115 fixes [BZ 2059107](https://bugzilla.redhat.com/show_bug.cgi?id=2059107)

### CODE REVIEW

**Comment by cybertron** [comment]
This lgtm. Do we want to link a bz so the bot can update status for us? Technically we need one for a 4.10 patch anyway, although I don't think that's actually configured on this repo.

**Comment by creydr** [comment]
/retitle [release-4.10] Bug 2046191: Rebase to upstream v0.64.7

**Comment by creydr** [comment]
/retitle [release-4.10] Bug 2059095: Rebase to upstream v0.64.7

**Comment by cybertron** [comment]
/lgtm
/hold

We will need to hold off on this until 4.10.0 ships. Otherwise should be ready to go.

**Comment by amalykhi** [comment]
backport to 4.10 looks good
/lgtm

**Comment by creydr** [comment]
> /lgtm /hold
> 
> We will need to hold off on this until 4.10.0 ships. Otherwise should be ready to go.

@cybertron: Any concerns unholding it now?

**Comment by cybertron** [comment]
/hold cancel

Nope, good to go now.

**Pull request merged**
