### PR TITLE
DNM: use openshift cert service

### PR DESCRIPTION
**Pull request by qinqon**
**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by qinqon** [comment]
We should rebase, the fix is upstream.

**Comment by mkowalski** [comment]
Bot will rebase. Sooner than later

**Pull request closed without merging**
