### PR TITLE
Bug 2046191: Rebase to upstream v0.64.6

### PR DESCRIPTION
**Pull request by creydr**
Inspired by the commit description for #243 

Identify carry commits:

```
git remote update
git log --oneline --no-merges v0.64.6..openshift/master
```

Note that the `UPSTREAM: <carry>:` prefix was added to any new commits to carry since the previous rebase. This will make new carry commits easy to identify alongside prior carry commits.

After identifying the carry commits, the next step is to create the new commit-tree that will be used for the rebase and then cherry pick the carry commits into the new branch.

The following commands cover these steps:

Process

```
$ git remote update # make sure we update our refs
$ git checkout v0.64.6 # upstream kubernetes-nmstate 0.65.0 commit tag
$ git checkout -b merge-tmp # create a branch to do our merge work from
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge nmstate/kubernetes-nmstate v0.64.6' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F -
deadbeef12345678 # id of new merge commit, output by the previous command
$ git branch merge-0.64.6 deadbeef12345678 # create a new branch for the cherry-pick work
$ git checkout merge-0.64.6 # make sure we are on the proper branch
$ git cherry-pick <carry commits>
```

* My 0.64.6 merge commit from the above process is (a6f0b34a2).
* With the merge-0.64.6 branch in place, I cherry picked the carry commits since `merge nmstate/kubernetes-nmstate v0.64.1` e37684083 (#243). 
* The commits `Remove initialization resource from CSV` (cccc287de) and `Remove initialization resource from 4.9 too` (4e1f7f6ef) were squashed into f1565c94f and prefixed with `UPSTREAM: <carry>:`

Carried Commits (applied bottom to top / oldest first):

* `UPSTREAM: <carry>: Add midstream approvers and reviewers` (6263f77b0)
* `UPSTREAM: <carry>: Add manifests for 4.7` (f678c07c3)
* `UPSTREAM: <carry>: Add manifests for 4.8` (4e75460ed)
* `UPSTREAM: <carry>: Add manifests for 4.9` (25cf7b9cf)
* `UPSTREAM: <carry>: Add manifests to .PHONY in Makefile` (51f205c9c)
* `UPSTREAM: <carry>: Add ocp-e2e-tests script` (e083843b7)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (d671f9ab0)
* `UPSTREAM: <carry>: Define the suggested namespace for NMState CR` (c64e54f27)
* `UPSTREAM: <carry>: Add machineconfigs before running e2e tests on OCP` (9ef5bcd8a)
* `UPSTREAM: <carry>: update naming convention` (ff2e1d613)
* `UPSTREAM: <carry>: Update dockerfile to match ART` (3747f3ffb)
* `UPSTREAM: <carry>: Remove serviceaccount manifest` (5b03040bd)
* `UPSTREAM: <carry>: Provide default NMState CR` (bbc9ef9d3)
* `UPSTREAM: <carry>: Skip e2e tests which are not supported on OVN` (e84ba0fa1)
* `UPSTREAM: <carry>: Add 4.10 release OLM manifests` (c11cbeabc)
* `UPSTREAM: <carry>: add arm64 to 4.10 CSV` (9d2073ac3)
* `UPSTREAM: <carry>: Add ppc64le and s390x to 4.10 CSV` (b812fb203)
* `UPSTREAM: <carry>: Fix JSON error in initialization resource` (1ecd17000)
* `UPSTREAM: <carry>: Update OWNERS` (2bcaac6c9)
* `UPSTREAM: <carry>: Switch to dnf in Openshift handler image` (53c1e643f)
* `UPSTREAM: <carry>: Add disconnected annotation for OperatorHub` (d0019d834)
* `UPSTREAM: <carry>: enable all archs in nmstate example CR` (95a7204a2)
* `UPSTREAM: <carry>: Add ssh proxy for e2e tests in CI` (2603108cf)
* `UPSTREAM: <carry>: Remove initialization resource from CSVs` (f1565c94f)
* `UPSTREAM: <carry>: Apply SCC in e2e tests when reinstalling operator in another namespace` (aa635d53a)
* `UPSTREAM: <carry>: Add make target to run operator e2e tests against ocp` (214be8f17)

**Release note**:
```release-note
Rebase to kubernetes-nmstate upstream v0.64.6
```

### CODE REVIEW

**Comment by cybertron** [comment]
/lgtm

Unfortunately, OVN-based deployments are likely to fail until https://github.com/openshift/machine-config-operator/pull/2934 merges. :-/

**Comment by creydr** [comment]
Closing in favor of #260.

**Pull request closed without merging**
