### PR TITLE
Rebase to kubernetes-nmstate v0.71.0

### PR DESCRIPTION
**Pull request by creydr**
Inspired by the commit description for #243 

Identify carry commits:

```
git remote update
git log --oneline --no-merges v0.71.0..openshift/master
```

Note that the `UPSTREAM: <carry>:` prefix was added to any new commits to carry since the previous rebase. This will make new carry commits easy to identify alongside prior carry commits.

After identifying the carry commits, the next step is to create the new commit-tree that will be used for the rebase and then cherry pick the carry commits into the new branch.

The following commands cover these steps:

Process

```
$ git remote update # make sure we update our refs
$ git checkout v0.71.0 # upstream kubernetes-nmstate 0.71.0 commit tag
$ git checkout -b merge-tmp # create a branch to do our merge work from
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge nmstate/kubernetes-nmstate v0.71.0' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F -
deadbeef12345678 # id of new merge commit, output by the previous command
$ git branch merge-0.71.0 deadbeef12345678 # create a new branch for the cherry-pick work
$ git checkout merge-0.71.0 # make sure we are on the proper branch
$ git cherry-pick <carry commits>
```

* My 0.71.0 merge commit from the above process is (84742ae5b).
* With the merge-0.71.0 branch in place, I cherry picked the carry commits since `merge nmstate/kubernetes-nmstate v0.67.0` 8d9f1c557 (#260). 

Carried Commits:

* `UPSTREAM: <carry>: Add midstream approvers and reviewers` (6a7d58343)
* `UPSTREAM: <carry>: Add manifests for 4.7` (501cf9043)
* `UPSTREAM: <carry>: Add manifests for 4.8` (fcac58d06)
* `UPSTREAM: <carry>: Add manifests for 4.9` (90410efd0)
* `UPSTREAM: <carry>: Add manifests to .PHONY in Makefile` (eeff5e4ca)
* `UPSTREAM: <carry>: Add ocp-e2e-tests script` (f9060680e)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (efa227e53)
* `UPSTREAM: <carry>: Define the suggested namespace for NMState CR` (95b57ac4a)
* `UPSTREAM: <carry>: Add machineconfigs before running e2e tests on OCP` (a99184758)
* `UPSTREAM: <carry>: update naming convention` (cb8690e0a)
* `UPSTREAM: <carry>: Update dockerfile to match ART` (aef7be0e3)
* `UPSTREAM: <carry>: Remove serviceaccount manifest` (4fe57588a)
* `UPSTREAM: <carry>: Provide default NMState CR` (f81f82333)
* `UPSTREAM: <carry>: Skip e2e tests which are not supported on OVN` (5f1b9b584)
* `UPSTREAM: <carry>: Add 4.10 release OLM manifests` (4c860923b)
* `UPSTREAM: <carry>: add arm64 to 4.10 CSV` (229014232)
* `UPSTREAM: <carry>: Add ppc64le and s390x to 4.10 CSV` (508f76bed)
* `UPSTREAM: <carry>: Fix JSON error in initialization resource` (9652e4f59)
* `UPSTREAM: <carry>: Update OWNERS` (2c83deab1)
* `UPSTREAM: <carry>: Switch to dnf in Openshift handler image` (a53ca4557)
* `UPSTREAM: <carry>: Add disconnected annotation for OperatorHub` (ceab56267)
* `UPSTREAM: <carry>: enable all archs in nmstate example CR` (4ce333051)
* `UPSTREAM: <carry>: Add ssh proxy for e2e tests in CI` (f73ee9329)
* `UPSTREAM: <carry>: Remove initialization resource from CSV` (f3a3de829)
* `UPSTREAM: <carry>: Apply SCC in e2e tests when reinstalling operator in another namespace` (de2462b89)
* `UPSTREAM: <carry>: Add make target to run operator e2e tests against ocp` (5d1c79910)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (839dc5481)
* `UPSTREAM: <carry>: Add operators app label in CSV` (ef4413790)
* `UPSTREAM: <carry>: Do not ignore parameters for ocp tests` (bcb43a63d)
* `UPSTREAM: <carry>: Add manifests for 4.11` (b528d6af2)
* `UPSTREAM: <carry>: Fix ssh-ci.sh for dualstack environments` (7a9505c18)
* `UPSTREAM: <carry>: Update Dockerfile images to match ART` (91e6418ed)
* `UPSTREAM: <carry>: Add qosClass to operator CSV` (2ae0e8418)
* `UPSTREAM: <carry>: add priority class to operator CSV` (9e5a033ca)
* `UPSTREAM: <carry>: Rerun flaky e2e tests` (22608ef27)

In addition I updated the CSV file so it aligns with the latest changes from this rebase (36e01dcf) and needed to update the e2e test run script for the operator in 30bcdfb3 because new operator e2e tests needed to reach the nodes.

**Included bug fixes:**
* https://bugzilla.redhat.com/show_bug.cgi?id=2075491
* https://bugzilla.redhat.com/show_bug.cgi?id=2069517
* https://bugzilla.redhat.com/show_bug.cgi?id=2067849
* https://bugzilla.redhat.com/show_bug.cgi?id=2022745
* https://bugzilla.redhat.com/show_bug.cgi?id=2053112
* https://bugzilla.redhat.com/show_bug.cgi?id=2053118

**Release note**:
```release-note
Rebase to kubernetes-nmstate upstream v0.71.0
```

### CODE REVIEW

**Comment by creydr** [comment]
@cybertron @dougsland @vpickard: the SDN e2e handler tests are passing again. Seems the nmstate issue is fixed and available in the builds :tada: 
The OVN tests passed too, but failed later on a must-gather issue :/ [1524645498013618176](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes-nmstate/272/pull-ci-openshift-kubernetes-nmstate-master-e2e-handler-ovn-ipv4/1524645498013618176)

```
....
INFO[2022-05-12T09:49:52Z] Step e2e-handler-ovn-ipv4-kubernetes-nmstate-e2e-handler succeeded after 1h46m30s. 
...
```
Can't retrigger currently due to a build issue: https://coreos.slack.com/archives/CBN38N3MW/p1652347345843039

/assign @cybertron @dougsland 
/this-is-fine

**Comment by cybertron** [comment]
/lgtm

My understanding is that the ovn tests were basically passing, and if the one failure was legit we can address that later. This fixes a lot of bugs so I think it's worth getting in now. Also, up until now we haven't even been testing ovn in ci so we're certainly no worse off than we were before.

**Pull request merged**
