### PR TITLE
Cherry-pick upstream k8s metrics and update manifests

### PR DESCRIPTION
**Pull request by mkowalski**

### CODE REVIEW

**Comment by mkowalski** [comment]
/override ci/prow/security

Will be handled as proper rebase. This PR here is only about generating manifests

**Comment by qinqon** [comment]
/retest-required

Something at CI is pretty wrong 
```
 * could not run steps: step e2e-handler-ovn-ipv4 failed: "e2e-handler-ovn-ipv4" test steps failed: "e2e-handler-ovn-ipv4" pod "e2e-handler-ovn-ipv4-kubernetes-nmstate-e2e-handler" failed: could not watch pod: the pod ci-op-2fr3lkdj/e2e-handler-ovn-ipv4-kubernetes-nmstate-e2e-handler failed after 2m11s (failed containers: test): ContainerFailed one or more containers exited

Container test exited with code 1, reason Error
---
E0420 16:23:10.780328      28 memcache.go:265] couldn't get current server API group list: Get "https://api.ostest.test.metalkube.org:6443/api?timeout=32s": proxyconnect tcp: dial tcp 128.31.20.106:8143: i/o timeout
E0420 16:23:40.781293      28 memcache.go:265] couldn't get current server API group list: Get "https://api.ostest.test.metalkube.org:6443/api?timeout=32s": proxyconnect tcp: dial tcp 128.31.20.106:8143: i/o timeout
E0420 16:24:10.782398      28 memcache.go:265] couldn't get current server API group list: Get "https://api.ostest.test.metalkube.org:6443/api?timeout=32s": proxyconnect tcp: dial tcp 128.31.20.106:8143: i/o timeout
E0420 16:24:40.783033      28 memcache.go:265] couldn't get current server API group list: Get "https://api.ostest.test.metalkube.org:6443/api?timeout=32s": proxyconnect tcp: dial tcp 128.31.20.106:8143: i/o timeout
Unable to connect to the server: proxyconnect tcp: dial tcp 128.31.20.106:8143: i/o timeout
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:84","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2024-04-20T16:24:40Z"}
error: failed to execute wrapped command: exit status 1
```

**Pull request merged**
